services:
  # Este contenedor es donde "vive" VS Code y el alumno escribe
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    network_mode: service:n8n # Conecta ambos contenedores por red local

  # Este es el servidor de n8n corriendo en segundo plano
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data:
