services:
  n8n:
    image: n8nio/n8n:1.82.3
    working_dir: /workspaces/n8n_docker_google
    volumes:
      - ..:/workspaces/n8n_docker_google:cached
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - N8N_EDITOR_BASE_URL=https://${CODESPACE_NAME}-5678.app.github.dev/
      - WEBHOOK_URL=https://${CODESPACE_NAME}-5678.app.github.dev/
    command: sh -c "sleep infinity"

volumes:
  n8n_data:
